version: "3"
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
services:
  redis1:
    image: redis
    networks:
      mynetwork:
        ipv4_address: 10.0.0.11
    ports:
    - 7000:6379
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis2:
    image: redis
    networks:
      mynetwork:
        ipv4_address: 10.0.0.12
    ports:
      - 7001:6379
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis3:
    image: redis
    networks:
      mynetwork:
        ipv4_address: 10.0.0.13
    ports:
      - 7002:6379
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis4:
    image: redis
    networks:
      mynetwork:
        ipv4_address: 10.0.0.14
    ports:
      - 7003:6379
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis5:
    image: redis
    networks:
      mynetwork:
        ipv4_address: 10.0.0.15
    ports:
      - 7004:6379
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis6:
    image: redis
    networks:
      mynetwork:
        ipv4_address: 10.0.0.16
    ports:
      - 7005:6379
    volumes:
      - ./redis.cluster.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-cluster:
    image: redis:latest
    command: redis-cli  -p 7000 --cluster create 10.0.0.11:6379 10.0.0.12:6379 10.0.0.13:6379 10.0.0.14:6379 10.0.0.15:6379 10.0.0.16:6379  --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
    networks:
      mynetwork:
        ipv4_address: 10.0.0.20